{
  imports = [
    ./blink.nix
    ./bufferline.nix
    ./colorizer.nix
    ./conform.nix
    ./fidget.nix
    ./grug-far.nix
    ./illuminate.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./mini-indentscope.nix
    ./mini-notify.nix
    ./mini.nix
    ./navic.nix
    ./nvim-surround.nix
    ./precognition.nix
    ./rustaceanvim.nix
    ./smartcolumn.nix
    ./snacks.nix
    ./treesitter.nix
    ./undotree.nix
    ./vimtex.nix
    ./web-devicons.nix
    ./which-key.nix
    ./yazi.nix
  ];
}
