# based on a file auto-generated by nix-init
{pkgs}: let
  inherit
    (pkgs)
    buildGoModule
    fetchFromGitHub
    lib
    ;
in
  buildGoModule rec {
    pname = "civ5-map-image";
    version = "unstable-2025-09-05";

    src = fetchFromGitHub {
      hash = "sha256-ilpHnzkF02l0yslNkoNy6gkCO3t85062Asak6jL5m0M=";
      owner = "samuelyuan";
      repo = "Civ5MapImage";
      rev = "2114f577f134a6c10b73764dba1df1d8a7fdd17d";
    };

    vendorHash = "sha256-kkVft+iZ9Hr2n9pL5d40sNspR3CbYUjrwoMBgwsBirg=";

    ldflags = ["-s" "-w"];

    meta = {
      description = "Convert Civ 5 map to an image";
      homepage = "https://github.com/samuelyuan/Civ5MapImage";
      license = lib.licenses.mit;
      mainProgram = "civ5-map-image";
      # maintainers = with lib.maintainers; [];
    };
  }
