# work environment layered on top of minimal/nicer tty
{
  imports = [
    ./app-alacritty.nix
    ./app-chromium.nix
    ./app-gimp.nix
    ./app-glance.nix
    ./app-inkscape.nix
    ./app-math
    ./app-neovide.nix
    ./app-nix-index.nix
    ./app-nwg-drawer.nix
    ./app-onlyoffice.nix
    ./app-pika.nix
    ./app-rnote.nix
    ./app-simple-scan.nix
    ./app-syncthing
    ./app-udiskie.nix
    ./app-vlc.nix
    ./app-zathura.nix
    ./hw-tablet.nix
    ./opt-mime.nix
    ./opt-stylix
    ./opt-xdg.nix
    ./suite-gnomeApps.nix
    ./suite-hyprEcosystem.nix
    ./suite-miscUtils.nix
    ./suite-qt.nix
    ./wm-hyprland
  ];
}
